---

_vendor:   ''
_app:      portfolio
_app_dir:  /srv/app
_app_host: "{{ _app ~ ('.' ~ _vendor if _vendor else '') }}"
_env:      dev

########
# Motd #
########

elao_motd_template: template/empty.j2
elao_motd:          Phillip

############
# Timezone #
############

elao_timezone: Etc/UTC

#######
# Env #
#######

elao_env:
  - SYMFONY_ENV: "{{ _env }}"

#######
# Apt #
#######

elao_apt_update: true

elao_apt_repositories: []

elao_apt_preferences:
  - git@backports
  - file: dotdeb
    template: preferences/dotdeb_low.j2
  - php@dotdeb_php56
  - nginx@nginx
  - nodejs@nodesource_0_12

elao_apt_packages:
  - name: g++

#######
# Ssh #
#######

elao_ssh_config_sshd_template: config/sshd/{{ _env }}.j2

elao_ssh_config_template: config/{{ _env }}.j2
elao_ssh_config: []

#######
# Git #
#######

elao_git_config_template: config/{{ _env }}.j2

#############
# Oh my zsh #
#############

elao_ohmyzsh_users:
  - user:     "{{ _user }}"
    template: users/{{ _env }}.j2
    config:
      - ZSH_THEME: elao-dev
      - plugins: (git debian common-aliases history history-substring-search npm bower)
      - |
        elao_php_xdebug () {
            if [[ $1 == on ]]; then sudo mv /etc/php5/fpm/conf.d/20-xdebug.ini.off /etc/php5/fpm/conf.d/20-xdebug.ini
            else sudo mv /etc/php5/fpm/conf.d/20-xdebug.ini /etc/php5/fpm/conf.d/20-xdebug.ini.off; fi
            sudo service php5-fpm restart
        }
      - cd {{ _app_dir }}

#########
# Files #
#########

elao_files: ~

##########
# Log.io #
##########

elao_logio_config_harvester:
  - nodeName: App
  - logStreams:
    - php:
      - "{{ elao_php_log_dir }}/error.log"
    - nginx:
      - "{{ elao_nginx_log_dir }}/app.access.log"
      - "{{ elao_nginx_log_dir }}/app.error.log"

#######
# Php #
#######

elao_php_sapis: ['cli', 'fpm']

elao_php_fpm_pools_exclusive: true
elao_php_fpm_pools:
  - file:     www.conf
    template: fpm_pools/www_{{ _env }}.conf.j2

elao_php_extensions:
  # Dev
  - xdebug
  # Symfony
  - intl
  - curl
  # App

elao_php_configs_exclusive: true
elao_php_configs:
  - file: 50-xdebug.ini
    template: configs/xdebug_{{ _env }}.ini.j2
  - file: 50-opcache.ini
    template: configs/opcache_{{ _env }}.ini.j2
  - file: 60-config.ini
    template: configs/{{ _env }}.ini.j2
    config:
      - date.timezone: UTC
      # App

#########
# Nginx #
#########

elao_nginx_config_template: config/http_{{ _env }}.conf.j2

elao_nginx_configs_exclusive: true
_nginx_configs:
  # Php fpm
  - file:     php_fpm_params
    template: configs/php_fpm_params_{{ _env }}.j2
  # Gzip
  - file:     gzip
    template: configs/gzip_{{ _env }}.j2
  # Default 404
  - file:     00-default.conf
    template: configs/server_{{ _env }}.conf.j2
    config:
      - return: 404
  # App static
  - file:     "{{ _app_host }}.conf"
    template: configs/server_{{ _env }}.conf.j2
    config:
      - server_name: "{{ _app_host }}.dev"
      - root:       "{{ _app_dir }}/dist"
      #- listen:     "{{ ansible_eth1.ipv4.address }}:80"
      - access_log: "{{ elao_nginx_log_dir }}/static.access.log"
      - error_log:  "{{ elao_nginx_log_dir }}/static.error.log"
      - include:     conf.d/gzip
      - charset:    "UTF-8"
  # App live
  - file:     "live.{{ _app_host }}.conf"
    template: configs/server_{{ _env }}.conf.j2
    config:
      - server_name: "live.{{ _app_host }}.dev"
      #- root:       "{{ _app_dir }}"
      #- listen:     "{{ ansible_eth1.ipv4.address }}:80"
      - access_log: "{{ elao_nginx_log_dir }}/live.access.log"
      - error_log:  "{{ elao_nginx_log_dir }}/live.error.log"
      - include:     conf.d/gzip
      - charset:    "UTF-8"
      - location /:
        - proxy_pass:         http://127.0.0.1:8000
        - proxy_http_version: "1.1"
        - proxy_set_header:   Host $host
        - proxy_set_header:   X-Real-IP $remote_addr
        - proxy_set_header:   X-Forwarded-For $proxy_add_x_forwarded_for

#######
# Npm #
#######

elao_npm_packages:
  - name:    gulp
    version: 3

#######
# Pip #
#######

elao_pip_packages:
  - name: Pygments

##############
# Supervisor #
##############

elao_supervisor_config_template: config/{{ _env }}.conf.j2

elao_supervisor_configs_exclusive: true
elao_supervisor_configs:
  - file:     inet-http-server.conf
    template: configs/inet_http_server_{{ _env }}.conf.j2
  - file:     gulp.conf
    template: configs/program_{{ _env }}.conf.j2
    config:
      - gulp:
        - command:         gulp watch
        - directory:       "{{ _app_dir }}"
        - user:            "vagrant"
        - autorestart:     true
        - stdout_logfile:  "{{ elao_supervisor_log_dir }}/app-worker-gulp.log"
        - redirect_stderr: true
