---

app_options:

  php_version:            '7.0' #5.4|5.5|5.6|7.0
  nodejs_version:         '6'   #0.10|0.12|4|5|6

  #mysql:                 false
  #mysql_version:         '5.6' #5.6|5.7
  #postgresql:            false
  #postgresql_version:    '9.5' #9.4|9.5
  #redis:                 false
  #mongodb:               false
  #mongodb_version:       '3.2' #3.0|3.2
  #elasticsearch:         false
  #elasticsearch_version: '1.7' #1.5|1.6|1.7|2

app_patterns:

  ############
  # Timezone #
  ############

  timezone_default: Etc/UTC

  ###############
  # Environment #
  ###############

  environment_variables: []
  #  - SYMFONY_ENV:           "{{ app.env }}"
  #  - APP_SECRET:            ThisTokenIsNotSoSecretChangeIt
  #  - APP_DATABASE_HOST:     127.0.0.1
  #  - APP_DATABASE_PORT:     null
  #  - APP_DATABASE_NAME:     app
  #  - APP_DATABASE_USER:     "{{ app.user }}"
  #  - APP_DATABASE_PASSWORD: null

  #########
  # Files #
  #########

  files_attributes: []
  #  - path:  "{{ app.dir }}{{ app.dir_release }}/var/logs"
  #    src:   "{{ app.log_dir }}"
  #    state: link_directory
  #  - path:  "{{ app.dir }}{{ app.dir_release }}/var/cache"
  #    src:   "{{ app.cache_dir }}"
  #    state: link_directory
  #  - path:  "{{ app.dir }}{{ app.dir_release }}/var/sessions"
  #    src:   "{{ app.sessions_dir }}"
  #    state: link_directory

  #######
  # Npm #
  #######

  npm_packages:
    - package: gulp
      version: 3
  ##  - gulpjs/gulp-cli#4.0
  #  - package: webpack
  #    version: 1
  #  - package: webpack
  #    version: 2.1.0-beta.13

  #######
  # Pip #
  #######

  pip_packages:
    - name: Pygments

  #######
  # Php #
  #######

  php_extensions:
    # Symfony
    - opcache
    - json
    - intl
    - xdebug
    - curl
    - mbstring
    - xml
    # Composer
    - zip
    # App

  php_configs:
    #- file: 50-xdebug.ini
    #  template: configs/xdebug_{{ env }}.ini.j2
    - file: app_opcache.ini
      template: configs/app_opcache.{{ env }}.j2
    - file: app.ini
      template: configs/app.{{ env }}.j2
      config:
        - date.timezone: UTC

  #########
  # Nginx #
  #########

  nginx_configs:
    # Php fpm
    - file:     app_php_fpm
      template: configs/app_php_fpm.{{ env }}.j2
    # Gzip
    - file:     app_gzip
      template: configs/app_gzip.{{ env }}.j2
    # App static
    - file:     "app.conf"
      #template: configs/server_{{ env }}.conf.j2
      config:
        - server:
          - server_name: "{{ app.host }}"
          - root:       "{{ app.dir }}{{ app.dir_release }}/dist"
          - access_log: "{{ app.log_dir }}/static.access.log"
          - error_log:  "{{ app.log_dir }}/static.error.log"
          - include:     conf.d/app_gzip
          - charset:    "UTF-8"
    # App live
    - file:     "live.conf"
      #template: configs/server_{{ env }}.conf.j2
      config:
        - server:
          - server_name: "live.{{ app.host }}"
          - root:       "{{ app.dir }}{{ app.dir_release }}/dist"
          - access_log: "{{ app.log_dir }}/live.access.log"
          - error_log:  "{{ app.log_dir }}/live.error.log"
          - include:     conf.d/app_gzip
          - charset:    "UTF-8"
          - location /:
            - proxy_pass:         http://127.0.0.1:8000
            - proxy_http_version: "1.1"
            - proxy_set_header:   Host $host
            - proxy_set_header:   X-Real-IP $remote_addr
            - proxy_set_header:   X-Forwarded-For $proxy_add_x_forwarded_for

  ########
  # Cron #
  ########

  #cron_files:
  #  - file: app
  #    user: "{{ app.user }}"
  #    environment:
  #      - SYMFONY_ENV: "{{ app.env }}"
  #    jobs:
  #      - name:   foo-bar
  #        job:    "cd {{ app.dir }}{{ app.dir_release }} && php bin/console app:foo:bar --no-interaction -vv >> {{ app.log_dir }}/cron.foo-bar.log 2>&1"
  #        minute: 0
  #        hour:   7
  #        # Dev
  #        state:  absent

  ##############
  # Supervisor #
  ##############

  supervisor_configs:
    - file:     gulp.conf
      template: configs/app_program.{{ env }}.j2
      config:
        - gulp:
          - command:         make watch
          - directory:       "{{ app.dir }}{{ app.dir_release }}"
          - user:            "{{ app.user }}"
          - stdout_logfile:  "{{ app.log_dir }}/app-worker-gulp.log"
          #- autorestart:     true
          #- redirect_stderr: true
    - file:     live.conf
      template: configs/app_program.{{ env }}.j2
      config:
        - live:
          - command:         make run
          - directory:       "{{ app.dir }}{{ app.dir_release }}"
          - user:            "{{ app.user }}"
          - stdout_logfile:  "{{ app.log_dir }}/app-worker-live.log"
          #- autorestart:     true
          #- redirect_stderr: true
