---

#######
# Dir #
#######

manala_deploy_dir: /srv/app

############
# Releases #
############

manala_deploy_releases: 5

############
# Strategy #
############

manala_deploy_strategy: git

manala_deploy_strategy_git_repo:    "{{ lookup('pipe','git config --get remote.origin.url') }}"
manala_deploy_strategy_git_version: master

##########
# Shared #
##########

manala_deploy_shared_files:
  - app/config/parameters.yml

manala_deploy_shared_dirs:
  - var/logs
  - var/sessions

##########
# Copied #
##########

manala_deploy_copied:
  - vendor

###########
# Removed #
###########

manala_deploy_removed:
  - web/app_dev.php
  - web/app_test.php

############
# Writable #
############

manala_deploy_writable_dirs_mode: ug=rwx,o=rx
manala_deploy_writable_dirs:
  - var/cache
  - var/logs
  - var/sessions

#########
# Tasks #
#########

manala_deploy_tasks__main:
  - make: install@prod
  - make: build@prod
